//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRC", "FK_CLIENTE_ENDERECO", "ENDERECO", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GRC.ENDERECO), "CLIENTE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GRC.CLIENTE))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRC", "FK_PEDIDO_CLIENTE", "CLIENTE", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GRC.CLIENTE), "PEDIDO", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GRC.PEDIDO))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRC", "FK_PEDIDO_ITEM_PEDIDO", "PEDIDO", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GRC.PEDIDO), "PEDIDO_ITEM", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GRC.PEDIDO_ITEM))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("GRC", "FK_PEDIDO_ITEM_PRODUTO", "PRODUTO", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GRC.PRODUTO), "PEDIDO_ITEM", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GRC.PEDIDO_ITEM))]

// Original file name:
// Generation date: 11/11/2012 21:32:42
namespace GRC
{
    
    /// <summary>
    /// There are no comments for GRCEntities in the schema.
    /// </summary>
    public partial class GRCEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new GRCEntities object using the connection string found in the 'GRCEntities' section of the application configuration file.
        /// </summary>
        public GRCEntities() : 
                base("name=GRCEntities", "GRCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GRCEntities object.
        /// </summary>
        public GRCEntities(string connectionString) : 
                base(connectionString, "GRCEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new GRCEntities object.
        /// </summary>
        public GRCEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "GRCEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<CLIENTE> CLIENTE
        {
            get
            {
                if ((this._CLIENTE == null))
                {
                    this._CLIENTE = base.CreateQuery<CLIENTE>("[CLIENTE]");
                }
                return this._CLIENTE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<CLIENTE> _CLIENTE;
        /// <summary>
        /// There are no comments for ENDERECO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ENDERECO> ENDERECO
        {
            get
            {
                if ((this._ENDERECO == null))
                {
                    this._ENDERECO = base.CreateQuery<ENDERECO>("[ENDERECO]");
                }
                return this._ENDERECO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ENDERECO> _ENDERECO;
        /// <summary>
        /// There are no comments for PEDIDO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PEDIDO> PEDIDO
        {
            get
            {
                if ((this._PEDIDO == null))
                {
                    this._PEDIDO = base.CreateQuery<PEDIDO>("[PEDIDO]");
                }
                return this._PEDIDO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PEDIDO> _PEDIDO;
        /// <summary>
        /// There are no comments for PEDIDO_ITEM in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PEDIDO_ITEM> PEDIDO_ITEM
        {
            get
            {
                if ((this._PEDIDO_ITEM == null))
                {
                    this._PEDIDO_ITEM = base.CreateQuery<PEDIDO_ITEM>("[PEDIDO_ITEM]");
                }
                return this._PEDIDO_ITEM;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PEDIDO_ITEM> _PEDIDO_ITEM;
        /// <summary>
        /// There are no comments for PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<PRODUTO> PRODUTO
        {
            get
            {
                if ((this._PRODUTO == null))
                {
                    this._PRODUTO = base.CreateQuery<PRODUTO>("[PRODUTO]");
                }
                return this._PRODUTO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<PRODUTO> _PRODUTO;
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCLIENTE(CLIENTE cLIENTE)
        {
            base.AddObject("CLIENTE", cLIENTE);
        }
        /// <summary>
        /// There are no comments for ENDERECO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToENDERECO(ENDERECO eNDERECO)
        {
            base.AddObject("ENDERECO", eNDERECO);
        }
        /// <summary>
        /// There are no comments for PEDIDO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPEDIDO(PEDIDO pEDIDO)
        {
            base.AddObject("PEDIDO", pEDIDO);
        }
        /// <summary>
        /// There are no comments for PEDIDO_ITEM in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPEDIDO_ITEM(PEDIDO_ITEM pEDIDO_ITEM)
        {
            base.AddObject("PEDIDO_ITEM", pEDIDO_ITEM);
        }
        /// <summary>
        /// There are no comments for PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPRODUTO(PRODUTO pRODUTO)
        {
            base.AddObject("PRODUTO", pRODUTO);
        }
    }
    /// <summary>
    /// There are no comments for GRC.CLIENTE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRC", Name="CLIENTE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CLIENTE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CLIENTE object.
        /// </summary>
        /// <param name="cODIGO">Initial value of CODIGO.</param>
        /// <param name="nOME">Initial value of NOME.</param>
        /// <param name="cPF">Initial value of CPF.</param>
        /// <param name="tELEFONE">Initial value of TELEFONE.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static CLIENTE CreateCLIENTE(int cODIGO, string nOME, long cPF, string tELEFONE)
        {
            CLIENTE cLIENTE = new CLIENTE();
            cLIENTE.CODIGO = cODIGO;
            cLIENTE.NOME = nOME;
            cLIENTE.CPF = cPF;
            cLIENTE.TELEFONE = tELEFONE;
            return cLIENTE;
        }
        /// <summary>
        /// There are no comments for property CODIGO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO
        {
            get
            {
                return this._CODIGO;
            }
            set
            {
                this.OnCODIGOChanging(value);
                this.ReportPropertyChanging("CODIGO");
                this._CODIGO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO");
                this.OnCODIGOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanged();
        /// <summary>
        /// There are no comments for property NOME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NOME
        {
            get
            {
                return this._NOME;
            }
            set
            {
                this.OnNOMEChanging(value);
                this.ReportPropertyChanging("NOME");
                this._NOME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NOME");
                this.OnNOMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NOME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNOMEChanged();
        /// <summary>
        /// There are no comments for property CPF in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public long CPF
        {
            get
            {
                return this._CPF;
            }
            set
            {
                this.OnCPFChanging(value);
                this.ReportPropertyChanging("CPF");
                this._CPF = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CPF");
                this.OnCPFChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private long _CPF;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCPFChanging(long value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCPFChanged();
        /// <summary>
        /// There are no comments for property TELEFONE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TELEFONE
        {
            get
            {
                return this._TELEFONE;
            }
            set
            {
                this.OnTELEFONEChanging(value);
                this.ReportPropertyChanging("TELEFONE");
                this._TELEFONE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TELEFONE");
                this.OnTELEFONEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TELEFONE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTELEFONEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTELEFONEChanged();
        /// <summary>
        /// There are no comments for property EMAIL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string EMAIL
        {
            get
            {
                return this._EMAIL;
            }
            set
            {
                this.OnEMAILChanging(value);
                this.ReportPropertyChanging("EMAIL");
                this._EMAIL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMAIL");
                this.OnEMAILChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _EMAIL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEMAILChanged();
        /// <summary>
        /// There are no comments for ENDERECO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_CLIENTE_ENDERECO", "ENDERECO")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ENDERECO ENDERECO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ENDERECO>("GRC.FK_CLIENTE_ENDERECO", "ENDERECO").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ENDERECO>("GRC.FK_CLIENTE_ENDERECO", "ENDERECO").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ENDERECO in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ENDERECO> ENDERECOReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ENDERECO>("GRC.FK_CLIENTE_ENDERECO", "ENDERECO");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ENDERECO>("GRC.FK_CLIENTE_ENDERECO", "ENDERECO", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PEDIDO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_CLIENTE", "PEDIDO")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PEDIDO> PEDIDO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PEDIDO>("GRC.FK_PEDIDO_CLIENTE", "PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PEDIDO>("GRC.FK_PEDIDO_CLIENTE", "PEDIDO", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRC.ENDERECO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRC", Name="ENDERECO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ENDERECO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ENDERECO object.
        /// </summary>
        /// <param name="cODIGO">Initial value of CODIGO.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ENDERECO CreateENDERECO(int cODIGO)
        {
            ENDERECO eNDERECO = new ENDERECO();
            eNDERECO.CODIGO = cODIGO;
            return eNDERECO;
        }
        /// <summary>
        /// There are no comments for property CODIGO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO
        {
            get
            {
                return this._CODIGO;
            }
            set
            {
                this.OnCODIGOChanging(value);
                this.ReportPropertyChanging("CODIGO");
                this._CODIGO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO");
                this.OnCODIGOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanged();
        /// <summary>
        /// There are no comments for property LOGRADOURO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string LOGRADOURO
        {
            get
            {
                return this._LOGRADOURO;
            }
            set
            {
                this.OnLOGRADOUROChanging(value);
                this.ReportPropertyChanging("LOGRADOURO");
                this._LOGRADOURO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LOGRADOURO");
                this.OnLOGRADOUROChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _LOGRADOURO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOGRADOUROChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOGRADOUROChanged();
        /// <summary>
        /// There are no comments for property NUMERO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> NUMERO
        {
            get
            {
                return this._NUMERO;
            }
            set
            {
                this.OnNUMEROChanging(value);
                this.ReportPropertyChanging("NUMERO");
                this._NUMERO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("NUMERO");
                this.OnNUMEROChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _NUMERO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNUMEROChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNUMEROChanged();
        /// <summary>
        /// There are no comments for property BAIRRO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string BAIRRO
        {
            get
            {
                return this._BAIRRO;
            }
            set
            {
                this.OnBAIRROChanging(value);
                this.ReportPropertyChanging("BAIRRO");
                this._BAIRRO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("BAIRRO");
                this.OnBAIRROChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _BAIRRO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBAIRROChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnBAIRROChanged();
        /// <summary>
        /// There are no comments for property CIDADE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CIDADE
        {
            get
            {
                return this._CIDADE;
            }
            set
            {
                this.OnCIDADEChanging(value);
                this.ReportPropertyChanging("CIDADE");
                this._CIDADE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CIDADE");
                this.OnCIDADEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CIDADE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCIDADEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCIDADEChanged();
        /// <summary>
        /// There are no comments for property ESTADO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ESTADO
        {
            get
            {
                return this._ESTADO;
            }
            set
            {
                this.OnESTADOChanging(value);
                this.ReportPropertyChanging("ESTADO");
                this._ESTADO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ESTADO");
                this.OnESTADOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ESTADO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnESTADOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnESTADOChanged();
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_CLIENTE_ENDERECO", "CLIENTE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<CLIENTE> CLIENTE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CLIENTE>("GRC.FK_CLIENTE_ENDERECO", "CLIENTE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<CLIENTE>("GRC.FK_CLIENTE_ENDERECO", "CLIENTE", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRC.PEDIDO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRC", Name="PEDIDO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PEDIDO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PEDIDO object.
        /// </summary>
        /// <param name="cODIGO">Initial value of CODIGO.</param>
        /// <param name="dATA">Initial value of DATA.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PEDIDO CreatePEDIDO(int cODIGO, global::System.DateTime dATA)
        {
            PEDIDO pEDIDO = new PEDIDO();
            pEDIDO.CODIGO = cODIGO;
            pEDIDO.DATA = dATA;
            return pEDIDO;
        }
        /// <summary>
        /// There are no comments for property CODIGO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO
        {
            get
            {
                return this._CODIGO;
            }
            set
            {
                this.OnCODIGOChanging(value);
                this.ReportPropertyChanging("CODIGO");
                this._CODIGO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO");
                this.OnCODIGOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanged();
        /// <summary>
        /// There are no comments for property DATA in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime DATA
        {
            get
            {
                return this._DATA;
            }
            set
            {
                this.OnDATAChanging(value);
                this.ReportPropertyChanging("DATA");
                this._DATA = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DATA");
                this.OnDATAChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _DATA;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDATAChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDATAChanged();
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_CLIENTE", "CLIENTE")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public CLIENTE CLIENTE
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTE>("GRC.FK_PEDIDO_CLIENTE", "CLIENTE").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTE>("GRC.FK_PEDIDO_CLIENTE", "CLIENTE").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CLIENTE in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<CLIENTE> CLIENTEReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CLIENTE>("GRC.FK_PEDIDO_CLIENTE", "CLIENTE");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CLIENTE>("GRC.FK_PEDIDO_CLIENTE", "CLIENTE", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PEDIDO_ITEM in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_ITEM_PEDIDO", "PEDIDO_ITEM")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PEDIDO_ITEM> PEDIDO_ITEM
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PEDIDO_ITEM>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO_ITEM");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PEDIDO_ITEM>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO_ITEM", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRC.PEDIDO_ITEM in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO_PRODUTO
    /// CODIGO_PEDIDO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRC", Name="PEDIDO_ITEM")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PEDIDO_ITEM : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PEDIDO_ITEM object.
        /// </summary>
        /// <param name="cODIGO_PRODUTO">Initial value of CODIGO_PRODUTO.</param>
        /// <param name="cODIGO_PEDIDO">Initial value of CODIGO_PEDIDO.</param>
        /// <param name="qUANTIDADE">Initial value of QUANTIDADE.</param>
        /// <param name="pRECO_UNIT">Initial value of PRECO_UNIT.</param>
        /// <param name="tOTAL">Initial value of TOTAL.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PEDIDO_ITEM CreatePEDIDO_ITEM(int cODIGO_PRODUTO, int cODIGO_PEDIDO, int qUANTIDADE, decimal pRECO_UNIT, decimal tOTAL)
        {
            PEDIDO_ITEM pEDIDO_ITEM = new PEDIDO_ITEM();
            pEDIDO_ITEM.CODIGO_PRODUTO = cODIGO_PRODUTO;
            pEDIDO_ITEM.CODIGO_PEDIDO = cODIGO_PEDIDO;
            pEDIDO_ITEM.QUANTIDADE = qUANTIDADE;
            pEDIDO_ITEM.PRECO_UNIT = pRECO_UNIT;
            pEDIDO_ITEM.TOTAL = tOTAL;
            return pEDIDO_ITEM;
        }
        /// <summary>
        /// There are no comments for property CODIGO_PRODUTO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO_PRODUTO
        {
            get
            {
                return this._CODIGO_PRODUTO;
            }
            set
            {
                this.OnCODIGO_PRODUTOChanging(value);
                this.ReportPropertyChanging("CODIGO_PRODUTO");
                this._CODIGO_PRODUTO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO_PRODUTO");
                this.OnCODIGO_PRODUTOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO_PRODUTO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_PRODUTOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_PRODUTOChanged();
        /// <summary>
        /// There are no comments for property CODIGO_PEDIDO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO_PEDIDO
        {
            get
            {
                return this._CODIGO_PEDIDO;
            }
            set
            {
                this.OnCODIGO_PEDIDOChanging(value);
                this.ReportPropertyChanging("CODIGO_PEDIDO");
                this._CODIGO_PEDIDO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO_PEDIDO");
                this.OnCODIGO_PEDIDOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO_PEDIDO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_PEDIDOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGO_PEDIDOChanged();
        /// <summary>
        /// There are no comments for property QUANTIDADE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int QUANTIDADE
        {
            get
            {
                return this._QUANTIDADE;
            }
            set
            {
                this.OnQUANTIDADEChanging(value);
                this.ReportPropertyChanging("QUANTIDADE");
                this._QUANTIDADE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QUANTIDADE");
                this.OnQUANTIDADEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _QUANTIDADE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQUANTIDADEChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQUANTIDADEChanged();
        /// <summary>
        /// There are no comments for property PRECO_UNIT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal PRECO_UNIT
        {
            get
            {
                return this._PRECO_UNIT;
            }
            set
            {
                this.OnPRECO_UNITChanging(value);
                this.ReportPropertyChanging("PRECO_UNIT");
                this._PRECO_UNIT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PRECO_UNIT");
                this.OnPRECO_UNITChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _PRECO_UNIT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRECO_UNITChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPRECO_UNITChanged();
        /// <summary>
        /// There are no comments for property TOTAL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal TOTAL
        {
            get
            {
                return this._TOTAL;
            }
            set
            {
                this.OnTOTALChanging(value);
                this.ReportPropertyChanging("TOTAL");
                this._TOTAL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TOTAL");
                this.OnTOTALChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _TOTAL;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTOTALChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTOTALChanged();
        /// <summary>
        /// There are no comments for PEDIDO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_ITEM_PEDIDO", "PEDIDO")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PEDIDO PEDIDO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PEDIDO>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PEDIDO>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PEDIDO in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PEDIDO> PEDIDOReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PEDIDO>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PEDIDO>("GRC.FK_PEDIDO_ITEM_PEDIDO", "PEDIDO", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PRODUTO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_ITEM_PRODUTO", "PRODUTO")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PRODUTO PRODUTO
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PRODUTO>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PRODUTO").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PRODUTO>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PRODUTO").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PRODUTO in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PRODUTO> PRODUTOReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PRODUTO>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PRODUTO");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PRODUTO>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PRODUTO", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for GRC.PRODUTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CODIGO
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="GRC", Name="PRODUTO")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PRODUTO : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PRODUTO object.
        /// </summary>
        /// <param name="cODIGO">Initial value of CODIGO.</param>
        /// <param name="dESCRICAO">Initial value of DESCRICAO.</param>
        /// <param name="vALOR">Initial value of VALOR.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static PRODUTO CreatePRODUTO(int cODIGO, string dESCRICAO, decimal vALOR)
        {
            PRODUTO pRODUTO = new PRODUTO();
            pRODUTO.CODIGO = cODIGO;
            pRODUTO.DESCRICAO = dESCRICAO;
            pRODUTO.VALOR = vALOR;
            return pRODUTO;
        }
        /// <summary>
        /// There are no comments for property CODIGO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int CODIGO
        {
            get
            {
                return this._CODIGO;
            }
            set
            {
                this.OnCODIGOChanging(value);
                this.ReportPropertyChanging("CODIGO");
                this._CODIGO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CODIGO");
                this.OnCODIGOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _CODIGO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCODIGOChanged();
        /// <summary>
        /// There are no comments for property DESCRICAO in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string DESCRICAO
        {
            get
            {
                return this._DESCRICAO;
            }
            set
            {
                this.OnDESCRICAOChanging(value);
                this.ReportPropertyChanging("DESCRICAO");
                this._DESCRICAO = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("DESCRICAO");
                this.OnDESCRICAOChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _DESCRICAO;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRICAOChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDESCRICAOChanged();
        /// <summary>
        /// There are no comments for property VALOR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal VALOR
        {
            get
            {
                return this._VALOR;
            }
            set
            {
                this.OnVALORChanging(value);
                this.ReportPropertyChanging("VALOR");
                this._VALOR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VALOR");
                this.OnVALORChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _VALOR;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVALORChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnVALORChanged();
        /// <summary>
        /// There are no comments for PEDIDO_ITEM in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("GRC", "FK_PEDIDO_ITEM_PRODUTO", "PEDIDO_ITEM")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PEDIDO_ITEM> PEDIDO_ITEM
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PEDIDO_ITEM>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PEDIDO_ITEM");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PEDIDO_ITEM>("GRC.FK_PEDIDO_ITEM_PRODUTO", "PEDIDO_ITEM", value);
                }
            }
        }
    }
}
